### PR TITLE
Compatibility with new version Rails and Concurrent Ruby

### PR DESCRIPTION
**Pull request by mgrachev**
This PR adds compatibility with rails 5.0.0.beta1 and concurrent-ruby 1.0.

1. `Concurrent::Atomic` is deprecated and instead need to use `Concurrent::AtomicReference` ([#277](https://github.com/ruby-concurrency/concurrent-ruby/pull/277));

2. In rails 5 added `ActionController::API`, which does not have a method` helper_method`, which is why the following error:

```
/Users/mgrachev/matchmaking/vendor/bundle/gems/peek-0.1.10/lib/peek/controller_helpers.rb:7:in `block in <module:ControllerHelpers>': undefined method `helper_method' for ActionController::API:Class (NoMethodError)
        from /Users/mgrachev/matchmaking/vendor/bundle/gems/activesupport-5.0.0.beta1/lib/active_support/concern.rb:120:in `class_eval'
        from /Users/mgrachev/matchmaking/vendor/bundle/gems/activesupport-5.0.0.beta1/lib/active_support/concern.rb:120:in `append_features'
        from /Users/mgrachev/matchmaking/vendor/bundle/gems/peek-0.1.10/lib/peek/railtie.rb:30:in `include'
        from /Users/mgrachev/matchmaking/vendor/bundle/gems/peek-0.1.10/lib/peek/railtie.rb:30:in `block (2 levels) in <class:Railtie>'
```

### CODE REVIEW

File: lib/peek/controller_helpers.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@ module ControllerHelpers
 
     included do
       prepend_before_filter :set_peek_request_id, :if => :peek_enabled?
-      helper_method :peek_enabled?
+      helper_method :peek_enabled? if respond_to? :helper_method
```
Comment (dewski) [inline lib/peek/controller_helpers.rb]: How does this work with backwards compatibility?

Comment (mgrachev) [inline lib/peek/controller_helpers.rb]: Works on rails 4.0.0 and above. In earlier versions, I get the following error:

```ruby
NoMethodError: undefined method `prepend_before_action' for ActionController::Base:Class
/Users/mgrachev/test_app/vendor/bundle/bundler/gems/peek-bb96e9b47bfd/lib/peek/controller_helpers.rb:6:in `block in <module:ControllerHelpers>'
/Users/mgrachev/test_app/vendor/bundle/gems/activesupport-3.2.0/lib/active_support/concern.rb:117:in `class_eval'
/Users/mgrachev/test_app/vendor/bundle/gems/activesupport-3.2.0/lib/active_support/concern.rb:117:in `append_features'
/Users/mgrachev/test_app/vendor/bundle/bundler/gems/peek-bb96e9b47bfd/lib/peek/railtie.rb:30:in `include'
/Users/mgrachev/test_app/vendor/bundle/bundler/gems/peek-bb96e9b47bfd/lib/peek/railtie.rb:30:in `block (2 levels) in <class:Railtie>
```

**Comment by mgrachev** [comment]
Updated
